# Generated by Django 5.1.3 on 2025-01-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Inventory Name')),
                ('logo', models.ImageField(upload_to='InventoryImages')),
                ('address', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('web_address', models.CharField(blank=True, max_length=150, null=True)),
                ('phone1', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number 2')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
