# Generated by Django 5.1.3 on 2025-01-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysetting',
            name='phone1',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='inventorysetting',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number 2'),
        ),
    ]
