# Generated by Django 5.1.3 on 2025-01-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorysetting_phone1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysetting',
            name='web_address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Web Address'),
        ),
    ]
