# Generated by Django 5.1.3 on 2025-01-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorysetting_web_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysetting',
            name='web_address',
            field=models.CharField(blank=True, help_text='Store website Address', max_length=150, null=True, verbose_name='Web Address'),
        ),
    ]
