# Generated by Django 5.1.3 on 2025-02-05 22:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelf',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
