# Generated by Django 5.1.3 on 2025-02-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shelf_created_shelf_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
