# Generated by Django 5.1.3 on 2025-02-09 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_stockadjustmenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_transferred', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('destination_shelf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_shelf', to='shop.shelf')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('source_shelf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_shelf', to='shop.shelf')),
            ],
        ),
    ]
