# nginx docker settings `dockerfile`
FROM nginx:latest

# Remove default configuration file provided by Nginx
COPY ./default.conf /etc/nginx/conf.d/default.conf

# Set the working directory
WORKDIR /usr/share/nginx/html

# Ensure media directory exists
RUN mkdir -p /usr/share/nginx/html/media

# Static and media files will be mounted from Docker volumes
